version: '3'

services: 
    router:
        build: .
        container_name: router
        tty: true
        privileged: true
        volumes:
            - ./src:/usr/local/router-shakyo
        networks:
            - bridge1
            - router-bridge

    vyos:
        build: ./vyos/ 
        container_name: vyos
        tty: true
        privileged: true
        networks:
            - bridge2
            - router-bridge

    host1:
        build: .
        container_name: host1
        tty: true
        privileged: true
        networks:
            - bridge1
        # volumes:
            # - ./src:/usr/local/router-shakyo
    
    host2:
        build: .
        container_name: host2
        tty: true
        privileged: true
        networks:
            - bridge2

networks: 
    bridge1:
        driver: bridge
    bridge2:
        driver: bridge
    router-bridge:
        driver: bridge
