version: '3'

services:
    vyos1:
        build: .
        privileged: true
        container_name: vyos1

    vyos2:
        build: .
        privileged: true
        container_name: vyos2

    host1:
        build: ./../
        privileged: true
        tty: true
        container_name: host1

    host2:
        build: ./../
        privileged: true
        tty: true
        container_name: host2
